export const deviceList = [
  { id: 'B4125', name: 'D2 Air X10', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B2819', name: 'D2 Charlie', highMemory: true, bikeRadar: true, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B3197', name: 'D2 Delta', highMemory: true, bikeRadar: true, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B3198', name: 'D2 Delta PX', highMemory: true, bikeRadar: true, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B3196', name: 'D2 Delta S', highMemory: true, bikeRadar: true, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B4079', name: 'D2 Mach 1', highMemory: true, bikeRadar: true, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B3499', name: 'Darth Vader', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: true, barometer: true },
  { id: 'B2859', name: 'Descent Mk1', highMemory: true, bikeRadar: true, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B3258', name: 'Descent Mk2 / Descent Mk2i', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3542', name: 'Descent Mk2 S', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B1836', name: 'Edge 1000 / Explore', highMemory: true, bikeRadar: false, touchScreen: true, settings: false, profileName: false, barometer: true },
  { id: 'B2713', name: 'Edge 1030', highMemory: true, bikeRadar: true, touchScreen: true, settings: false, profileName: true, barometer: true },
  { id: 'B3095', name: 'Edge 1030 / Bontrager', highMemory: true, bikeRadar: true, touchScreen: true, settings: false, profileName: true, barometer: true },
  { id: 'B3570', name: 'Edge 1030 Plus', highMemory: true, bikeRadar: true, touchScreen: true, settings: false, profileName: true, barometer: true },
  { id: 'B2909', name: 'Edge 130', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B3558', name: 'Edge 130 Plus', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B2067', name: 'Edge 520', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B3112', name: 'Edge 520 Plus', highMemory: true, bikeRadar: true, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B3121', name: 'Edge 530', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B2530', name: 'Edge 820 / Explore', highMemory: true, bikeRadar: true, touchScreen: true, settings: false, profileName: false, barometer: true },
  { id: 'B3122', name: 'Edge 830', highMemory: true, bikeRadar: true, touchScreen: true, settings: false, profileName: true, barometer: true },
  { id: 'B3011', name: 'Edge Explore', highMemory: true, bikeRadar: true, touchScreen: true, settings: false, profileName: false, barometer: false },
  { id: 'B3638', name: 'Enduro', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: true, barometer: true },
  { id: 'B3944', name: 'epix (Gen 2)', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B2697', name: 'fēnix 5 / quatix 5', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B3110', name: 'fēnix 5 Plus', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  //{ id: 'B2544', name: 'fēnix 5S', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B2900', name: 'fēnix 5S Plus', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B2604', name: 'fēnix 5X / tactix Charlie', highMemory: true, bikeRadar: true, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B3111', name: 'fēnix 5X Plus', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3289', name: 'fēnix 6 / 6 Solar / 6 Dual Power', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: true, barometer: true },
  { id: 'B3290', name: 'fēnix 6 Pro / 6 Sapphire / 6 Pro Solar / 6 Pro Dual Power / quatix 6', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3287', name: 'fēnix 6S / 6S Solar / 6S Dual Power', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: true, barometer: true },
  { id: 'B3288', name: 'fēnix 6S Pro / 6S Sapphire / 6S Pro Solar / 6S Pro Dual Power', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3291', name: 'fēnix 6X Pro / 6X Sapphire / 6X Pro Solar / tactix Delta Sapphire / Delta Solar / Delta Solar - Ballistics Edition / quatix 6X / 6X Solar / 6X Dual Power', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3906', name: 'fēnix 7', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3905', name: 'fēnix 7S', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3907', name: 'fēnix 7X', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3501', name: 'First Avenger', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: true, barometer: true },
  { id: 'B3076', name: 'Forerunner 245', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: true, barometer: false },
  { id: 'B3077', name: 'Forerunner 245 Music', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: false },
  { id: 'B2886', name: 'Forerunner 645', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B2888', name: 'Forerunner 645 Music', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3589', name: 'Forerunner 745', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B2691', name: 'Forerunner 935', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B3113', name: 'Forerunner 945', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3652', name: 'Forerunner 945 LTE', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3624', name: 'MARQ Adventurer', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3251', name: 'MARQ Athlete', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3247', name: 'MARQ Aviator', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3248', name: 'MARQ Captain / MARQ Captain: American Magic Edition', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3249', name: 'MARQ Commander', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3246', name: 'MARQ Driver', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3250', name: 'MARQ Expedition', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3739', name: 'MARQ Golfer', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3703', name: 'Venu 2', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3851', name: 'Venu 2 Plus', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B3704', name: 'Venu 2S', highMemory: true, bikeRadar: true, touchScreen: false, settings: true, profileName: true, barometer: true },
  { id: 'B2700', name: 'vívoactive 3', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B3473', name: 'vívoactive 3 Mercedes-Benz Collection', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: false, barometer: true },
  { id: 'B2988', name: 'vívoactive 3 Music', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: true, barometer: true },
  { id: 'B3066', name: 'vívoactive 3 Music LTE', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: true, barometer: true },
  { id: 'B3225', name: 'vívoactive 4', highMemory: false, bikeRadar: false, touchScreen: false, settings: false, profileName: true, barometer: true }
];

let map = {};
deviceList.forEach(item => map[item.id] = item);

export const deviceMap = map;

export const getDevice = (device) => {
  return device && deviceMap[device];
};
